// swift-tools-version:5.3
// Generated by release_rxswift_binaries.sh
// RxSwift 6.10.0 — https://github.com/pishija/RxSwiftBinaries

import PackageDescription

let package = Package(
    name: "RxSwift",
    platforms: [
        .iOS(.v13),
        .macOS(.v10_15),
        .tvOS(.v13),
        .watchOS(.v6)
    ],
    products: [
        .library(name: "RxSwift", targets: ["RxSwift"]) ,
        .library(name: "RxCocoa", targets: ["RxCocoa"]) ,
        .library(name: "RxRelay", targets: ["RxRelay"]) ,
        .library(name: "RxTest", targets: ["RxTest"]) ,
        .library(name: "RxBlocking", targets: ["RxBlocking"])
    ],
    targets: [
        .binaryTarget(
            name: "RxSwift",
            url: "https://github.com/pishija/RxSwiftBinaries/releases/download/rxswift-6.10.0/RxSwift.xcframework.zip",
            checksum: "67195debada509756a1162de13c17ed8779abd734947d555110256f2e70935ba"
        ),
        .binaryTarget(
            name: "RxCocoa",
            url: "https://github.com/pishija/RxSwiftBinaries/releases/download/rxswift-6.10.0/RxCocoa.xcframework.zip",
            checksum: "2558c4e87bc0a964be9233a214b46ebbdfe8fb8376dadd70c4c9d79877284014"
        ),
        .binaryTarget(
            name: "RxRelay",
            url: "https://github.com/pishija/RxSwiftBinaries/releases/download/rxswift-6.10.0/RxRelay.xcframework.zip",
            checksum: "6b1ad553500a00e07b970cc31b83a4640075ff75cf4b0c27b372363c57fd6a74"
        ),
        .binaryTarget(
            name: "RxTest",
            url: "https://github.com/pishija/RxSwiftBinaries/releases/download/rxswift-6.10.0/RxTest.xcframework.zip",
            checksum: "ca6e83492a5bdd127b7804e291ddb66c602dd4bbdb4dc8c0b04d70d2b1c93428"
        ),
        .binaryTarget(
            name: "RxBlocking",
            url: "https://github.com/pishija/RxSwiftBinaries/releases/download/rxswift-6.10.0/RxBlocking.xcframework.zip",
            checksum: "0ed12c45ffae241a9a6f3500ecbac88d2c03e7ba9ebfdfca43b29082e9b8f967"
        )
    ]
)
