// swift-tools-version:5.3
// Generated by release_rxswift_binaries.sh
// RxSwift 6.10.0 — https://github.com/pishija/RxSwiftBinaries

import PackageDescription

let package = Package(
    name: "RxSwift",
    platforms: [
        .iOS(.v13),
        .macOS(.v10_15),
        .tvOS(.v13),
        .watchOS(.v6)
    ],
    products: [
        .library(name: "RxSwift", targets: ["RxSwift"]) ,
        .library(name: "RxCocoa", targets: ["RxCocoa"]) ,
        .library(name: "RxRelay", targets: ["RxRelay"]) ,
        .library(name: "RxTest", targets: ["RxTest"]) ,
        .library(name: "RxBlocking", targets: ["RxBlocking"])
    ],
    targets: [
        .binaryTarget(
            name: "RxSwift",
            url: "https://github.com/pishija/RxSwiftBinaries/releases/download/rxswift-6.10.0/RxSwift.xcframework.zip",
            checksum: "59ef50c3aeb1e049ab5f15e0853465a98c5bf468d834829c165948cd15bf95fa"
        ),
        .binaryTarget(
            name: "RxCocoa",
            url: "https://github.com/pishija/RxSwiftBinaries/releases/download/rxswift-6.10.0/RxCocoa.xcframework.zip",
            checksum: "1b5b185fb973a33bcc95d701a789ff1ce5165cf5cd68faa068faaa6bcb7fec9b"
        ),
        .binaryTarget(
            name: "RxRelay",
            url: "https://github.com/pishija/RxSwiftBinaries/releases/download/rxswift-6.10.0/RxRelay.xcframework.zip",
            checksum: "5e039d867803838b9a57669f8ea4389a951348fc9fc5db441ffc23221e74c2d2"
        ),
        .binaryTarget(
            name: "RxTest",
            url: "https://github.com/pishija/RxSwiftBinaries/releases/download/rxswift-6.10.0/RxTest.xcframework.zip",
            checksum: "58f63a6a4dbb27fe4eae3212b1ba0fbf060a52dbe99938114fa700f7e771a3bf"
        ),
        .binaryTarget(
            name: "RxBlocking",
            url: "https://github.com/pishija/RxSwiftBinaries/releases/download/rxswift-6.10.0/RxBlocking.xcframework.zip",
            checksum: "1892592b216a1e101ba42ee212215c8f5a18fb12e586eff7e7c5eda7ed5c712d"
        )
    ]
)
