// swift-tools-version:5.3
// Generated by release_rxswift_binaries.sh
// RxSwift 6.10.0 — https://github.com/pishija/RxSwiftBinaries

import PackageDescription

let package = Package(
    name: "RxSwift",
    platforms: [
        .iOS(.v13),
        .macOS(.v10_15),
        .tvOS(.v13),
        .watchOS(.v6)
    ],
    products: [
        .library(name: "RxSwift", targets: ["RxSwift"]),
        .library(name: "RxCocoa", targets: ["RxCocoa"]),
        .library(name: "RxRelay", targets: ["RxRelay"]),
        .library(name: "RxTest", targets: ["RxTest"]),
        .library(name: "RxBlocking", targets: ["RxBlocking"])
    ],
    targets: [
        .binaryTarget(
            name: "RxSwift",
            url: "https://github.com/pishija/RxSwiftBinaries/releases/download/rxswift-6.10.0/RxSwift.xcframework.zip",
            checksum: "6e6a1cfe5c759994fab1fcab0ba43e753b8a3036992642151689bbc1c0496e28"
        ),
        .binaryTarget(
            name: "RxCocoa",
            url: "https://github.com/pishija/RxSwiftBinaries/releases/download/rxswift-6.10.0/RxCocoa.xcframework.zip",
            checksum: "55fdab8fa0831bdd63228a598521b81f09edc1a0282f2b15a72a41db344df685"
        ),
        .binaryTarget(
            name: "RxRelay",
            url: "https://github.com/pishija/RxSwiftBinaries/releases/download/rxswift-6.10.0/RxRelay.xcframework.zip",
            checksum: "a7ef691720fed5938ae88ac95406549c5a4c91cabb1fa9e59cc53cb692284dc9"
        ),
        .binaryTarget(
            name: "RxTest",
            url: "https://github.com/pishija/RxSwiftBinaries/releases/download/rxswift-6.10.0/RxTest.xcframework.zip",
            checksum: "b7fb5057c4c7bf9046e4e5b7e8d2da6c45d728dcf8f8afdbbaea5408cbb89971"
        ),
        .binaryTarget(
            name: "RxBlocking",
            url: "https://github.com/pishija/RxSwiftBinaries/releases/download/rxswift-6.10.0/RxBlocking.xcframework.zip",
            checksum: "95167be14682816f4c6a7b6a663d0209a9ed8fac924ea0c735b60f4b2a3d96fa"
        )
    ]
)
